name: DAsistent Bots

on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:

jobs:
  main-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run main bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          REF_BOT_TOKEN: ${{ secrets.REF_BOT_TOKEN }}
        run: python bot.py

  ref-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run referral bot
        env:
          REF_BOT_TOKEN: ${{ secrets.REF_BOT_TOKEN }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python ref_bot.py